// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleAPI.Context;

#nullable disable

namespace OrmSampleAPI.Migrations
{
    [DbContext(typeof(LiberaryDbContext))]
    [Migration("20260618153750_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SampleAPI.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            Biography = "نویسنده برجسته داستان مدرن فارسی.",
                            BirthDate = new DateOnly(1903, 2, 17),
                            FirstName = "صادق",
                            LastName = "هدایت"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            Biography = "نویسنده و مترجم ایرانی و خالق رمان سووشون.",
                            BirthDate = new DateOnly(1921, 4, 28),
                            FirstName = "سیمین",
                            LastName = "دانشور"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Biography = "رمان‌نویس معاصر ایرانی و نویسنده کلیدر.",
                            BirthDate = new DateOnly(1940, 8, 1),
                            FirstName = "محمود",
                            LastName = "دولت‌آبادی"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            Biography = "نویسنده تاثیرگذار داستان‌نویسی معاصر فارسی.",
                            BirthDate = new DateOnly(1938, 3, 16),
                            FirstName = "هوشنگ",
                            LastName = "گلشیری"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            Biography = "شاعر و نویسنده بزرگ فارسی‌زبان.",
                            FirstName = "سعدی",
                            LastName = "شیرازی"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333336"),
                            Biography = "غزل‌سرای نامدار ایرانی.",
                            FirstName = "حافظ",
                            LastName = "شیرازی"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333337"),
                            Biography = "سراینده شاهنامه و احیاگر زبان فارسی.",
                            FirstName = "ابوالقاسم",
                            LastName = "فردوسی"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333338"),
                            Biography = "شاعر نوگرای معاصر ایران.",
                            BirthDate = new DateOnly(1935, 1, 5),
                            FirstName = "فروغ",
                            LastName = "فرخزاد"
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ReplacementCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.HasIndex("Title");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "رمان کوتاه و تاثیرگذار صادق هدایت در ادبیات مدرن فارسی.",
                            Edition = 5,
                            IsDeleted = false,
                            Isbn = "9789640010011",
                            Pages = 128,
                            PublicationYear = 1937,
                            PublisherId = new Guid("22222222-2222-2222-2222-222222222223"),
                            ReplacementCost = 350000m,
                            Title = "بوف کور"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "رمانی اجتماعی از سیمین دانشور درباره شیراز در سال‌های جنگ جهانی دوم.",
                            Edition = 12,
                            IsDeleted = false,
                            Isbn = "9789640010028",
                            Pages = 304,
                            PublicationYear = 1969,
                            PublisherId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ReplacementCost = 520000m,
                            Title = "سووشون"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "رمان بلند محمود دولت‌آبادی درباره زندگی روستایی و عشایری خراسان.",
                            Edition = 8,
                            IsDeleted = false,
                            Isbn = "9789640010035",
                            Pages = 2836,
                            PublicationYear = 1984,
                            PublisherId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ReplacementCost = 2200000m,
                            Title = "کلیدر"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "رمانی ساختارمند از هوشنگ گلشیری درباره فروپاشی یک خاندان قاجاری.",
                            Edition = 7,
                            IsDeleted = false,
                            Isbn = "9789640010042",
                            Pages = 112,
                            PublicationYear = 1969,
                            PublisherId = new Guid("22222222-2222-2222-2222-222222222223"),
                            ReplacementCost = 310000m,
                            Title = "شازده احتجاب"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "نثر آهنگین و حکایت‌های اخلاقی سعدی شیرازی.",
                            Edition = 20,
                            IsDeleted = false,
                            Isbn = "9789640010059",
                            Pages = 360,
                            PublicationYear = 1258,
                            PublisherId = new Guid("22222222-2222-2222-2222-222222222221"),
                            ReplacementCost = 480000m,
                            Title = "گلستان سعدی"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555556"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "گزیده غزل‌های حافظ شیرازی با شرح واژگان.",
                            Edition = 15,
                            IsDeleted = false,
                            Isbn = "9789640010066",
                            Pages = 640,
                            PublicationYear = 1399,
                            PublisherId = new Guid("22222222-2222-2222-2222-222222222221"),
                            ReplacementCost = 680000m,
                            Title = "دیوان حافظ"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555557"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "متن برگزیده شاهنامه برای مطالعه عمومی.",
                            Edition = 10,
                            IsDeleted = false,
                            Isbn = "9789640010073",
                            Pages = 1216,
                            PublicationYear = 1010,
                            PublisherId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ReplacementCost = 1350000m,
                            Title = "شاهنامه فردوسی"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555558"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مجموعه‌ای از شعرهای فروغ فرخزاد در جریان شعر نو فارسی.",
                            Edition = 9,
                            IsDeleted = false,
                            Isbn = "9789640010080",
                            Pages = 176,
                            PublicationYear = 1964,
                            PublisherId = new Guid("22222222-2222-2222-2222-222222222224"),
                            ReplacementCost = 390000m,
                            Title = "تولدی دیگر"
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.BookAuthor", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId", "SortOrder");

                    b.ToTable("BookAuthors", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555551"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333331"),
                            SortOrder = 1
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555552"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333332"),
                            SortOrder = 1
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555553"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SortOrder = 1
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555554"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333334"),
                            SortOrder = 1
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555555"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333335"),
                            SortOrder = 1
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555556"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333336"),
                            SortOrder = 1
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555557"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333337"),
                            SortOrder = 1
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555558"),
                            AuthorId = new Guid("33333333-3333-3333-3333-333333333338"),
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.BookCategory", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555551"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444441")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555551"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444446")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555552"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444441")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555552"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444446")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555553"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444441")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555553"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444446")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555554"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444441")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555554"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444446")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444442")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444445")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555556"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444442")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555556"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444443")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555557"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444442")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555557"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555558"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444443")
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555558"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444446")
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.BookCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AcquiredOn")
                        .HasColumnType("date");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InventoryLabel")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComputedColumnSql("[Barcode] + ' @ ' + [ShelfLocation]");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShelfLocation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("BookId");

                    b.HasIndex("BranchId");

                    b.ToTable("BookCopies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            AcquiredOn = new DateOnly(2024, 2, 10),
                            Barcode = "IR-BOF-001",
                            BookId = new Guid("55555555-5555-5555-5555-555555555551"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PurchasePrice = 250000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "تهران-A1",
                            Status = "Rented"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            AcquiredOn = new DateOnly(2024, 2, 10),
                            Barcode = "IR-BOF-002",
                            BookId = new Guid("55555555-5555-5555-5555-555555555551"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PurchasePrice = 250000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "شیراز-B2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            AcquiredOn = new DateOnly(2024, 3, 5),
                            Barcode = "IR-SUV-001",
                            BookId = new Guid("55555555-5555-5555-5555-555555555552"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PurchasePrice = 410000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "شیراز-A3",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666664"),
                            AcquiredOn = new DateOnly(2024, 3, 5),
                            Barcode = "IR-SUV-002",
                            BookId = new Guid("55555555-5555-5555-5555-555555555552"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PurchasePrice = 410000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "تهران-C1",
                            Status = "Reserved"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666665"),
                            AcquiredOn = new DateOnly(2024, 4, 12),
                            Barcode = "IR-KEL-001",
                            BookId = new Guid("55555555-5555-5555-5555-555555555553"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PurchasePrice = 1850000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "تهران-D4",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AcquiredOn = new DateOnly(2024, 4, 12),
                            Barcode = "IR-KEL-002",
                            BookId = new Guid("55555555-5555-5555-5555-555555555553"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111113"),
                            PurchasePrice = 1850000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "اصفهان-E1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666667"),
                            AcquiredOn = new DateOnly(2024, 5, 3),
                            Barcode = "IR-SHAZ-001",
                            BookId = new Guid("55555555-5555-5555-5555-555555555554"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PurchasePrice = 230000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "تهران-B1",
                            Status = "Rented"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666668"),
                            AcquiredOn = new DateOnly(2024, 5, 3),
                            Barcode = "IR-SHAZ-002",
                            BookId = new Guid("55555555-5555-5555-5555-555555555554"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111113"),
                            PurchasePrice = 230000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "اصفهان-A2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666669"),
                            AcquiredOn = new DateOnly(2024, 6, 1),
                            Barcode = "IR-GOL-001",
                            BookId = new Guid("55555555-5555-5555-5555-555555555555"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PurchasePrice = 360000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "شیراز-G1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666670"),
                            AcquiredOn = new DateOnly(2024, 6, 1),
                            Barcode = "IR-GOL-002",
                            BookId = new Guid("55555555-5555-5555-5555-555555555555"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111113"),
                            PurchasePrice = 360000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "اصفهان-C3",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666671"),
                            AcquiredOn = new DateOnly(2024, 7, 8),
                            Barcode = "IR-HAF-001",
                            BookId = new Guid("55555555-5555-5555-5555-555555555556"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PurchasePrice = 520000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "شیراز-H1",
                            Status = "Reserved"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666672"),
                            AcquiredOn = new DateOnly(2024, 7, 8),
                            Barcode = "IR-HAF-002",
                            BookId = new Guid("55555555-5555-5555-5555-555555555556"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PurchasePrice = 520000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "تهران-F2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666673"),
                            AcquiredOn = new DateOnly(2024, 8, 20),
                            Barcode = "IR-SHN-001",
                            BookId = new Guid("55555555-5555-5555-5555-555555555557"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PurchasePrice = 1100000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "تهران-S1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666674"),
                            AcquiredOn = new DateOnly(2024, 8, 20),
                            Barcode = "IR-SHN-002",
                            BookId = new Guid("55555555-5555-5555-5555-555555555557"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111113"),
                            PurchasePrice = 1100000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "اصفهان-S2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666675"),
                            AcquiredOn = new DateOnly(2024, 9, 14),
                            Barcode = "IR-FOR-001",
                            BookId = new Guid("55555555-5555-5555-5555-555555555558"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PurchasePrice = 290000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "تهران-P1",
                            Status = "Reserved"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666676"),
                            AcquiredOn = new DateOnly(2024, 9, 14),
                            Barcode = "IR-FOR-002",
                            BookId = new Guid("55555555-5555-5555-5555-555555555558"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111112"),
                            PurchasePrice = 290000m,
                            RowVersion = new byte[0],
                            ShelfLocation = "شیراز-P3",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            Description = "رمان‌های فارسی و آثار داستانی بلند.",
                            Name = "رمان"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            Description = "آثار ماندگار ادبیات فارسی.",
                            Name = "ادبیات کلاسیک"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            Description = "مجموعه‌های شعر کلاسیک و معاصر.",
                            Name = "شعر"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "آثار حماسی و اسطوره‌ای.",
                            Name = "حماسه"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            Description = "داستان‌های کوتاه فارسی.",
                            Name = "داستان کوتاه"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444446"),
                            Description = "آثار نویسندگان معاصر ایران.",
                            Name = "ادبیات معاصر"
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.LibraryBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "کتابخانه مرکزی تهران",
                            Phone = "+98-21-88990011"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Name = "کتابخانه حافظ شیراز",
                            Phone = "+98-71-32220011"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Name = "کتابخانه نقش جهان اصفهان",
                            Phone = "+98-31-36660011"
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.LibraryUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("LibraryUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("LibraryUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SampleAPI.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publishers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Name = "انتشارات امیرکبیر",
                            Website = "https://amirkabirpub.ir"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "انتشارات سخن",
                            Website = "https://sokhanpub.net"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Name = "نشر نیلوفر",
                            Website = "https://niloofarbooks.com"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Name = "نشر مرکز",
                            Website = "https://markazpub.com"
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RentalNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("RentedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RentalNumber")
                        .IsUnique();

                    b.HasIndex("StaffId");

                    b.ToTable("Rentals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999991"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerId = new Guid("77777777-7777-7777-7777-777777777771"),
                            DueAtUtc = new DateTime(2026, 6, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            RentalNumber = "IR-RNT-2026-0001",
                            RentedAtUtc = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            StaffId = new Guid("88888888-8888-8888-8888-888888888881"),
                            Status = "Open"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999993"),
                            BranchId = new Guid("11111111-1111-1111-1111-111111111113"),
                            ClosedAtUtc = new DateTime(2026, 5, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("77777777-7777-7777-7777-777777777774"),
                            DueAtUtc = new DateTime(2026, 5, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            RentalNumber = "IR-RNT-2026-0002",
                            RentedAtUtc = new DateTime(2026, 5, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            StaffId = new Guid("88888888-8888-8888-8888-888888888883"),
                            Status = "Closed"
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.RentalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookCopyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DailyLateFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<decimal>("LateFeeCharged")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("RentalId");

                    b.ToTable("RentalLines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999992"),
                            BookCopyId = new Guid("66666666-6666-6666-6666-666666666661"),
                            DailyLateFee = 25000m,
                            IsReturned = false,
                            LateFeeCharged = 0m,
                            RentalId = new Guid("99999999-9999-9999-9999-999999999991"),
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999994"),
                            BookCopyId = new Guid("66666666-6666-6666-6666-666666666667"),
                            DailyLateFee = 25000m,
                            IsReturned = true,
                            LateFeeCharged = 0m,
                            RentalId = new Guid("99999999-9999-9999-9999-999999999993"),
                            ReturnedAtUtc = new DateTime(2026, 5, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookCopyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("CustomerId", "BookCopyId", "Status");

                    b.ToTable("Reservations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            BookCopyId = new Guid("66666666-6666-6666-6666-666666666671"),
                            CustomerId = new Guid("77777777-7777-7777-7777-777777777772"),
                            ExpiresAtUtc = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAtUtc = new DateTime(2026, 6, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            BookCopyId = new Guid("66666666-6666-6666-6666-666666666675"),
                            CustomerId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ExpiresAtUtc = new DateTime(2026, 6, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            ReservedAtUtc = new DateTime(2026, 6, 4, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("BookId", "CustomerId")
                        .IsUnique();

                    b.ToTable("Reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "[Rating] BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            BookId = new Guid("55555555-5555-5555-5555-555555555551"),
                            Comment = "فضاسازی بوف کور هنوز تکان‌دهنده و متفاوت است.",
                            CreatedAtUtc = new DateTime(2026, 6, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("77777777-7777-7777-7777-777777777772"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            BookId = new Guid("55555555-5555-5555-5555-555555555552"),
                            Comment = "روایت شیراز و شخصیت‌پردازی زری بسیار ماندگار است.",
                            CreatedAtUtc = new DateTime(2026, 6, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("77777777-7777-7777-7777-777777777771"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            BookId = new Guid("55555555-5555-5555-5555-555555555553"),
                            Comment = "طولانی اما پرجزئیات و ارزشمند.",
                            CreatedAtUtc = new DateTime(2026, 6, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("77777777-7777-7777-7777-777777777773"),
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            BookId = new Guid("55555555-5555-5555-5555-555555555556"),
                            Comment = "نسخه خوش‌خوان و مناسب برای مراجعه روزانه.",
                            CreatedAtUtc = new DateTime(2026, 6, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("77777777-7777-7777-7777-777777777775"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5"),
                            BookId = new Guid("55555555-5555-5555-5555-555555555557"),
                            Comment = "برای شروع مطالعه شاهنامه انتخاب خوبی است.",
                            CreatedAtUtc = new DateTime(2026, 6, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("77777777-7777-7777-7777-777777777778"),
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb6"),
                            BookId = new Guid("55555555-5555-5555-5555-555555555558"),
                            Comment = "شعرها زنده، مستقیم و تاثیرگذارند.",
                            CreatedAtUtc = new DateTime(2026, 6, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rating = 4
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.Customer", b =>
                {
                    b.HasBaseType("SampleAPI.Entities.LibraryUser");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("MembershipNumber")
                        .IsUnique()
                        .HasFilter("[MembershipNumber] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mina.ahmadi@example.ir",
                            FirstName = "مینا",
                            LastName = "احمدی",
                            Phone = "+98-912-100-1001",
                            JoinedOn = new DateOnly(2025, 1, 12),
                            MembershipNumber = "IR-MBR-1001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777772"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omid.rahimi@example.ir",
                            FirstName = "امید",
                            LastName = "رحیمی",
                            Phone = "+98-912-100-1002",
                            JoinedOn = new DateOnly(2025, 2, 20),
                            MembershipNumber = "IR-MBR-1002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777773"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "niloofar.kazemi@example.ir",
                            FirstName = "نیلوفر",
                            LastName = "کاظمی",
                            Phone = "+98-912-100-1003",
                            JoinedOn = new DateOnly(2025, 3, 8),
                            MembershipNumber = "IR-MBR-1003",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777774"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "reza.mousavi@example.ir",
                            FirstName = "رضا",
                            LastName = "موسوی",
                            Phone = "+98-912-100-1004",
                            JoinedOn = new DateOnly(2025, 4, 18),
                            MembershipNumber = "IR-MBR-1004",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777775"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.noori@example.ir",
                            FirstName = "سارا",
                            LastName = "نوری",
                            Phone = "+98-912-100-1005",
                            JoinedOn = new DateOnly(2025, 5, 4),
                            MembershipNumber = "IR-MBR-1005",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777776"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kaveh.moradi@example.ir",
                            FirstName = "کاوه",
                            LastName = "مرادی",
                            Phone = "+98-912-100-1006",
                            JoinedOn = new DateOnly(2025, 6, 10),
                            MembershipNumber = "IR-MBR-1006",
                            Status = "Suspended"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "leila.sadeghi@example.ir",
                            FirstName = "لیلا",
                            LastName = "صادقی",
                            Phone = "+98-912-100-1007",
                            JoinedOn = new DateOnly(2025, 7, 22),
                            MembershipNumber = "IR-MBR-1007",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777778"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "arash.karimi@example.ir",
                            FirstName = "آرش",
                            LastName = "کریمی",
                            Phone = "+98-912-100-1008",
                            JoinedOn = new DateOnly(2025, 8, 15),
                            MembershipNumber = "IR-MBR-1008",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.Staff", b =>
                {
                    b.HasBaseType("SampleAPI.Entities.LibraryUser");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("HiredOn")
                        .HasColumnType("date");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasFilter("[EmployeeNumber] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Staff");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.yousefi@persian-library.local",
                            FirstName = "سارا",
                            LastName = "یوسفی",
                            Phone = "+98-21-8899-2001",
                            EmployeeNumber = "IR-EMP-001",
                            HiredOn = new DateOnly(2023, 4, 1)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888882"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mehrdad.jafari@persian-library.local",
                            FirstName = "مهرداد",
                            LastName = "جعفری",
                            Phone = "+98-71-3222-2002",
                            EmployeeNumber = "IR-EMP-002",
                            HiredOn = new DateOnly(2023, 9, 10)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888883"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "parisa.hosseini@persian-library.local",
                            FirstName = "پریسا",
                            LastName = "حسینی",
                            Phone = "+98-31-3666-2003",
                            EmployeeNumber = "IR-EMP-003",
                            HiredOn = new DateOnly(2024, 2, 5)
                        });
                });

            modelBuilder.Entity("SampleAPI.Entities.Book", b =>
                {
                    b.HasOne("SampleAPI.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("SampleAPI.Entities.BookAuthor", b =>
                {
                    b.HasOne("SampleAPI.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleAPI.Entities.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("SampleAPI.Entities.BookCategory", b =>
                {
                    b.HasOne("SampleAPI.Entities.Book", "Book")
                        .WithMany("Categories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleAPI.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SampleAPI.Entities.BookCopy", b =>
                {
                    b.HasOne("SampleAPI.Entities.Book", "Book")
                        .WithMany("Copies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleAPI.Entities.LibraryBranch", "Branch")
                        .WithMany("Copies")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SampleAPI.Entities.LibraryBranch", b =>
                {
                    b.OwnsOne("SampleAPI.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("LibraryBranchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("nvarchar(180)")
                                .HasColumnName("Street");

                            b1.HasKey("LibraryBranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("LibraryBranchId");

                            b1.HasData(
                                new
                                {
                                    LibraryBranchId = new Guid("11111111-1111-1111-1111-111111111111"),
                                    City = "تهران",
                                    Country = "ایران",
                                    PostalCode = "1417933161",
                                    State = "تهران",
                                    Street = "خیابان انقلاب، نبش وصال"
                                },
                                new
                                {
                                    LibraryBranchId = new Guid("11111111-1111-1111-1111-111111111112"),
                                    City = "شیراز",
                                    Country = "ایران",
                                    PostalCode = "7136453111",
                                    State = "فارس",
                                    Street = "خیابان حافظیه، روبروی باغ جهان‌نما"
                                },
                                new
                                {
                                    LibraryBranchId = new Guid("11111111-1111-1111-1111-111111111113"),
                                    City = "اصفهان",
                                    Country = "ایران",
                                    PostalCode = "8146734611",
                                    State = "اصفهان",
                                    Street = "میدان نقش جهان، گذر کتاب"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("SampleAPI.Entities.Rental", b =>
                {
                    b.HasOne("SampleAPI.Entities.LibraryBranch", "Branch")
                        .WithMany("Rentals")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SampleAPI.Entities.Customer", "Customer")
                        .WithMany("Rentals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SampleAPI.Entities.Staff", "Staff")
                        .WithMany("Rentals")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SampleAPI.Entities.RentalLine", b =>
                {
                    b.HasOne("SampleAPI.Entities.BookCopy", "BookCopy")
                        .WithMany("RentalLines")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SampleAPI.Entities.Rental", "Rental")
                        .WithMany("Lines")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("SampleAPI.Entities.Reservation", b =>
                {
                    b.HasOne("SampleAPI.Entities.BookCopy", "BookCopy")
                        .WithMany("Reservations")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SampleAPI.Entities.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SampleAPI.Entities.Review", b =>
                {
                    b.HasOne("SampleAPI.Entities.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleAPI.Entities.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SampleAPI.Entities.Customer", b =>
                {
                    b.OwnsOne("SampleAPI.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("nvarchar(180)")
                                .HasColumnName("Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("LibraryUsers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("77777777-7777-7777-7777-777777777771"),
                                    City = "تهران",
                                    Country = "ایران",
                                    PostalCode = "1587654312",
                                    State = "تهران",
                                    Street = "خیابان مطهری، پلاک ۱۲"
                                },
                                new
                                {
                                    CustomerId = new Guid("77777777-7777-7777-7777-777777777772"),
                                    City = "تهران",
                                    Country = "ایران",
                                    PostalCode = "1418845671",
                                    State = "تهران",
                                    Street = "بلوار کشاورز، پلاک ۴۵"
                                },
                                new
                                {
                                    CustomerId = new Guid("77777777-7777-7777-7777-777777777773"),
                                    City = "شیراز",
                                    Country = "ایران",
                                    PostalCode = "7188832145",
                                    State = "فارس",
                                    Street = "خیابان قصردشت، کوچه سرو"
                                },
                                new
                                {
                                    CustomerId = new Guid("77777777-7777-7777-7777-777777777774"),
                                    City = "اصفهان",
                                    Country = "ایران",
                                    PostalCode = "8174678912",
                                    State = "اصفهان",
                                    Street = "خیابان چهارباغ بالا، پلاک ۹"
                                },
                                new
                                {
                                    CustomerId = new Guid("77777777-7777-7777-7777-777777777775"),
                                    City = "تهران",
                                    Country = "ایران",
                                    PostalCode = "1967743215",
                                    State = "تهران",
                                    Street = "خیابان ولیعصر، کوچه نیلوفر"
                                },
                                new
                                {
                                    CustomerId = new Guid("77777777-7777-7777-7777-777777777776"),
                                    City = "شیراز",
                                    Country = "ایران",
                                    PostalCode = "7134889123",
                                    State = "فارس",
                                    Street = "خیابان زند، پلاک ۱۸"
                                },
                                new
                                {
                                    CustomerId = new Guid("77777777-7777-7777-7777-777777777777"),
                                    City = "اصفهان",
                                    Country = "ایران",
                                    PostalCode = "8145672341",
                                    State = "اصفهان",
                                    Street = "خیابان آمادگاه، پلاک ۲۲"
                                },
                                new
                                {
                                    CustomerId = new Guid("77777777-7777-7777-7777-777777777778"),
                                    City = "تهران",
                                    Country = "ایران",
                                    PostalCode = "1934678911",
                                    State = "تهران",
                                    Street = "خیابان شریعتی، پلاک ۷۰"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("SampleAPI.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("SampleAPI.Entities.Book", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Categories");

                    b.Navigation("Copies");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SampleAPI.Entities.BookCopy", b =>
                {
                    b.Navigation("RentalLines");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SampleAPI.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("SampleAPI.Entities.LibraryBranch", b =>
                {
                    b.Navigation("Copies");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("SampleAPI.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("SampleAPI.Entities.Rental", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SampleAPI.Entities.Customer", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SampleAPI.Entities.Staff", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
